[yts]
host = "https://en.yts-official.mx"
order_by = "rating"
quality = 1080

[opensubs]
enable = true
language = "es"

[general]
download_folder = "/path/to/movies"
table_border_color = "240"
table_selection_fg_color = "15"
table_selection_bg_color = "240"
spinner_color = "15"
download_color = "245"
